#!/usr/bin/env python3
"""Generate flag->set_focus / flag->add_perk injectors for Lifestyle Prodigy GUI bypass."""

from __future__ import annotations

import re
from pathlib import Path

MOD_ROOT = (Path(__file__).resolve().parents[1] / "lasombra_court")
OUT_FILE = MOD_ROOT / "common" / "scripted_effects" / "zz_cosla_prodigy_flag_injectors.txt"

ROOTS = [
    Path(r"D:\Games\steamapps\common\Crusader Kings III\game\common"),
    Path(r"D:\Games\steamapps\workshop\content\1158310\2216659254\common"),
    MOD_ROOT / "common",
]

SKIP_KEYS = {
    "desc",
    "trigger",
    "effect",
    "modifier",
    "is_shown",
    "is_valid",
    "potential",
    "ai_will_do",
    "parent",
    "icon",
    "name",
    "position",
    "tree",
    "lifestyle",
    "auto_selection_weight",
    "can_be_picked",
    "character_modifier",
    "custom_tooltip",
    "animation",
}


def strip_line_comments(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if "#" not in line:
            lines.append(line)
            continue
        in_str = False
        out = []
        for ch in line:
            if ch == '"':
                in_str = not in_str
            if ch == "#" and not in_str:
                break
            out.append(ch)
        lines.append("".join(out))
    return "\n".join(lines)


def extract_top_level_keys(text: str) -> list[str]:
    text = strip_line_comments(text)
    keys: list[str] = []
    depth = 0
    pattern = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\{")
    pos = 0
    n = len(text)
    while pos < n:
        if depth == 0:
            m = pattern.search(text, pos)
            if not m:
                break
            while pos < m.start():
                c = text[pos]
                if c == "{":
                    depth += 1
                elif c == "}":
                    depth -= 1
                pos += 1
            if depth != 0:
                continue
            keys.append(m.group(1))
            pos = m.end()
            depth = 1
        else:
            c = text[pos]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
            pos += 1
    return keys


def collect_keys(subdir: str) -> list[str]:
    found: set[str] = set()
    for root in ROOTS:
        folder = root / subdir
        if not folder.exists():
            continue
        for path in folder.rglob("*.txt"):
            if "test" in path.name.lower():
                continue
            raw = path.read_text(encoding="utf-8-sig", errors="replace")
            for key in extract_top_level_keys(raw):
                if key in SKIP_KEYS:
                    continue
                if key.startswith("POD_") and subdir == "focuses":
                    continue
                found.add(key)
    return sorted(found)


def main() -> None:
    focuses = collect_keys("focuses")
    perks = collect_keys("lifestyle_perks")

    lines = [
        "# AUTO-GENERATED by tools/generate_prodigy_lifestyle_injectors.py — do not edit by hand.",
        "# Maps scope:flag (from GUI MakeScopeFlag) to set_focus / add_perk literals.",
        "",
        "cosla_prodigy_try_set_focus = {",
        "\tif = {",
        "\t\tlimit = { scope:flag = flag:$FOCUS$ }",
        "\t\tset_focus = $FOCUS$",
        "\t}",
        "}",
        "",
        "cosla_prodigy_try_add_perk = {",
        "\tif = {",
        "\t\tlimit = {",
        "\t\t\tscope:flag = flag:$PERK$",
        "\t\t\tNOT = { has_perk = $PERK$ }",
        "\t\t}",
        "\t\tadd_perk = $PERK$",
        "\t}",
        "}",
        "",
        "cosla_prodigy_focus_flag_injector = {",
    ]
    for focus in focuses:
        lines.append(f"\tcosla_prodigy_try_set_focus = {{ FOCUS = {focus} }}")
    lines.append("}")
    lines.append("")
    lines.append("cosla_prodigy_perk_flag_injector = {")
    for perk in perks:
        lines.append(f"\tcosla_prodigy_try_add_perk = {{ PERK = {perk} }}")
    lines.append("}")
    lines.append("")

    body = "\n".join(lines)
    OUT_FILE.write_text("\ufeff" + body, encoding="utf-8")
    print(f"Wrote {OUT_FILE}")
    print(f"  focuses: {len(focuses)}")
    print(f"  perks:   {len(perks)}")


if __name__ == "__main__":
    main()
